#python3 get.py ../auth.json
#python3 count_nearby.py ../auth.json   #keyError: 'location_point'

#python3 add_address.py ../auth.json
#python3 add_zip_long_lat.py ../auth.json
#python3 store_location_point.py ../auth.json

#python3 clean.py ../auth.json

#python3 fix_datetime.py ../auth.json
#python3 merge.py ../auth.json

#python3 output_counts_json.py ../auth.json
#python3 output_all_counts_per_zip.py ../auth.json
#python3 output_day_time_counts_json.py ../auth.json
#python3 output_violations_per_zip.py ../auth.json

python3 scoring_areas.py ../auth.json  #list z[] not defined
#python3 calc_ticket_fe_corr.py ../auth.json
